### ISSUE TITLE
Ktuvit Implementation

### ISSUE THREAD

**Issue by TwilightMercy** [Nitzantomer1998/StremioHebSubs#7]
Hi,
I will edit in the following days with full details on Ktuvit implementation. 

Until then, because I don't know very well what metadata you get from Stremio, can you post here a full example of all the metadata parameters you get?

For example: Imdb ID, season, episode, title, original title, TVShowTitle, year, etc...

One example from playing through default Stremio catalogs (default Cinemeta addon),

Abd another example from TMdb addon, configured on Hebrew language. 
https://94c8cb9f702d-tmdb-addon.baby-beamup.club/configure

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/a8d3640b-7816-4ef1-8bc8-6d88667f57f8)

This is relevant for Ktuvit, since IMDb ID only isn't enough, as opposed to Wizdom/OpenSubtitles API.

**Comment by Nitzantomer1998** [comment]
@TwilightMercy, thank you for your suggestion. After extensive consideration and testing, I've decided that the method to obtain subtitles from "Ktuvit" is not viable. While the links provided offer some guidance, the process they describe involves filtering an **HTML** page to retrieve subtitles, which is:
- Highly inefficient
- Unprofessional and poor practice
- Lacking in performance

Given these issues and considering that we already have "Wizdom" and "OpenSubtitles" implemented efficiently through their **official APIs**, I have decided to cancel the implementation of "Ktuvit" for now. The current providers already offer a high-quality and diverse range of subtitles for both old and new movies and TV series effectively.

I have reached out to "Ktuvit" to request an official API, as their website currently displays outdated information, and the existing methods involve browser calls and HTML traversal, which are not suitable for a reliable service.

Note: The reason I'm okay with not implementing "Ktuvit" right now is that retrieving the same subtitles from Ktuvit takes 5x longer compared to getting them from Wizdom or OpenSubtitles.

**Comment by Nitzantomer1998** [comment]
After reconsidering, I have decided to implement Ktuvit. However, its performance will be suboptimal for now as it is based on the "ktuvit-api" package.

A self-optimized version will be developed and implemented in the near future.

**Comment by TwilightMercy** [comment]
Thank you very much, appreciated
