### ISSUE TITLE
Project Name Suggestions

### ISSUE THREAD

**Issue by Nitzantomer1998** [Nitzantomer1998/StremioHebSubs#9]
Currently, the name is **Universal Hebrew Subtitles**. While it originally seemed to fit its purpose, I have started to dislike it because it is too long and the term "Universal" usually implies inclusion of all languages. My intention was mainly to create a Stremio Addon with all the **Hebrew** subtitle sources.

I’m considering making a final name change as follows:
- GitHub name: StremioHebSubs – This name includes "Stremio" and succinctly describes its purpose, making it clear to everyone.
- Stremio name: HebrewSubs, or HebSubs – There's no need to include "Stremio" in the internal name for obvious reason.

I would love to hear suggestions on this topic.

**Comment by Nitzantomer1998** [comment]
In response to a @TwilightMercy comment in [Issue #5](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/issues/5#issuecomment-2122939168)

> Will the link stay "wizdom" or will be changed to "universal-hebrew-subtitles" / something like that? 

As you may know, this project began with the goal of implementing Wizdom subtitles for Stremio. Due to higher demand than expected, I started integrating more Hebrew sources into the addon and considering name changes. However, since I'm using a free tier to host my application, I face restrictions that prevent updating the URL, so it remains "wizdom" and has limited performance.

Another issue is that, because of the free tier hosting, **the addon will be down from May 25th until the end of the month**. After that, I'll switch to a paid subscription, allowing the addon to be up 24/7 with better performance.

Additionally, even if I wanted to change the URL, Stremio can't update the current addon, it would create a new one, leaving the old users (around 4,000 in 10 days) stranded.

I have submitted an issue requesting a feature to update the URL if you are the owner [Issue #281](https://github.com/Stremio/stremio-addon-sdk/issues/281). Let's wait and see what happens.

**Comment by TwilightMercy** [comment]
> - GitHub name: StremioHebSubs – This name includes "Stremio" and succinctly describes its purpose, making it clear to everyone.
> 
> - Stremio name: HebrewSubs, or HebSubs – There's no need to include "Stremio" in the internal name for obvious reason.


GitHub name:
StremioAllHebSubs
Stremio name: All Hebrew Subs

**Comment by Nitzantomer1998** [comment]
> You have no problem to buy paid subscription for the addon? That's blessed of course, but just out of curiosity.

> From what I know, a lot of the addons uses free Stremio beamup service for hosting free addons. (That's only I know about it, nothing more)
It is viable solution?

I host the addon on a website called **Render**, which I've used extensively for several projects. Render provides an easy way to access my logs and monitor my application's usage, ensuring everything is running smoothly and allowing me to track and prevent errors. In my opinion, this is essential. It's also quite affordable—although it's free most of the time, I only need to pay around $0.5 for a day after i have maxed my free tier each month. So, it's manageable.

So from next month there wont be any downtime, but this month sadly there will.

**Comment by Nitzantomer1998** [comment]
The chosen names are now official:

- GitHub: StremioHebSubs
- Stremio: HebSubs
